# Arithmetic Operation

In [1]:
import numpy as np

var = np.array([1,2,3,4])

varadd = var+3

print(varadd)

[4 5 6 7]


In [2]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = var1+var2

print(varadd)

[2 4 6 8]


# 2D ARRAY

In [3]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])
print(var21)
print(var22)

varadd2 = var21*var22

print(varadd2)

[[1 2 3 4]
 [1 2 3 4]]
[[1 2 3 4]
 [1 2 3 4]]
[[ 1  4  9 16]
 [ 1  4  9 16]]


# Operation

In [13]:
num = np.array([1,2,3,4,5,3,2])

print("MAX:-",np.max(num),np.argmax(num))
print("MIN:-",np.min(num),np.argmin(num))
print("Sqrt:-", np.sqrt(num))

MAX:- 5 4
MIN:- 1 0
Sqrt:- [1.         1.41421356 1.73205081 2.         2.23606798 1.73205081
 1.41421356]


In [12]:
var1 = np.array([[2,1,3],[9,5,6]])

print(np.min(var1,axis = 0)) #this is row wise minimum
print(np.min(var1,axis = 1))#this is coulumn wise minimum

[2 1 3]
[1 5]


In [16]:
var2 = np.array([1,2,3])

print(np.sin(var2))
print(np.cos(var2))
print(np.cumsum(var2))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[1 3 6]
