# DATA TYPE

In [2]:
import numpy as np

var = np.array([1,2,3,4])

print("Data_type",var.dtype)

ModuleNotFoundError: No module named 'numpy'

In [2]:
var = np.array([1.0,2.0,6.9])

print("Data_type",var.dtype)

Data_type float64


In [4]:
var = np.array(["A","B"])

print("Data_type",var.dtype)

Data_type <U1


In [5]:
var = np.array([1,2,3,4,"A","B"])

print("Data_type",var.dtype)

Data_type <U11


In [12]:
x = np.array([1,2,3,4],dtype = np.int8)

print("Data_type",x.dtype)
print(x)

Data_type int8
[1 2 3 4]


In [14]:
x1 = np.array([1,2,3,4],dtype = "f")

print("Data_type",x1.dtype)
print(x1)

Data_type float32
[1. 2. 3. 4.]


In [15]:
x2 = np.array([1,2,3,4],dtype = np.int64)

new = np.float32(x2)

print("Data_type: ",x2.dtype)
print("Data_type: ",new.dtype)
print(x2)
print(new)

Data_type:  int64
Data_type:  float32
[1 2 3 4]
[1. 2. 3. 4.]


In [17]:
x2 = np.array([1,2,3,4],dtype = np.int32)

new = np.float32(x2)
new_one = np.int_(new)

print("Data_type: ",x2.dtype)
print("Data_type: ",new.dtype)
print("Data_type: ",new_one.dtype)
print(x2)
print(new)
print(new_one)

Data_type:  int32
Data_type:  float32
Data_type:  int32
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [18]:
x3 = np.array([1,2,3,4],dtype = "f")

new_1 = x3.astype(float)

print(x3)
print(new_1)

[1. 2. 3. 4.]
[1. 2. 3. 4.]
