# iteration

In [1]:
import numpy as np

var = np.array([9,8,7,6,5,4])

print(var)
print()

for i in var:
    print(i)

[9 8 7 6 5 4]

9
8
7
6
5
4


In [2]:
var1 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(var1)
print()

for j in var1:
    print(j)

print()

for k in var1:
    for l in k:
        print(l)

[[1 2 3 4 5]
 [1 2 3 4 5]]

[1 2 3 4 5]
[1 2 3 4 5]

1
2
3
4
5
1
2
3
4
5


In [3]:
var3 = np.array([[[9,8,7,6],[1,2,3,4]]])
print(var3)
print(var3.ndim)
print()

for i,d in np.ndenumerate(var3):
    print(i,d)

[[[9 8 7 6]
  [1 2 3 4]]]
3

(0, 0, 0) 9
(0, 0, 1) 8
(0, 0, 2) 7
(0, 0, 3) 6
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4
