# join array

In [1]:
import numpy as np

var = np.array([1,2,3,4])
var1 = np.array([9,8,7,6])

ar = np.concatenate((var,var1))

print(ar)

[1 2 3 4 9 8 7 6]


In [4]:
vr = np.array([[1,2],[3,4]])
vr1 = np.array([[9,8],[7,6]])

ar_new = np.concatenate((vr,vr1),axis=1)

print(ar)
print()
print(vr1)
print()
print(ar_new)

[1 2 3 4 9 8 7 6]

[[9 8]
 [7 6]]

[[1 2 9 8]
 [3 4 7 6]]


In [5]:
var_1 = np.array([1,2,3,4])
var_2 = np.array([9,8,7,6])

a_new = np.stack((var,var1),axis=1)

print(a_new)

[[1 9]
 [2 8]
 [3 7]
 [4 6]]
