In [3]:
import numpy as np

x=np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
y=[1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [5]:
l = []

for i in range(1,5):
    int_1 = int(input("enter :"))
    l.append(int_1)
    
print(np.array(l))

enter :11
enter :12
enter :23
enter :34
[11 12 23 34]


In [6]:
ar2=np.array([[1,2,3,4],[3,64,234,564]])
print(ar2)
print(ar2.ndim)

[[  1   2   3   4]
 [  3  64 234 564]]
2


In [7]:
ar3=np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3
