# Random

# Rand()

In [9]:
import numpy as np

var = np.random.rand(4)
print(var)

[0.02662693 0.15868003 0.39570503 0.77088211]


In [11]:
var1 = np.random.rand(2,5)

print(var1)

[[0.39167938 0.90961542 0.99052204 0.69370523 0.6084464 ]
 [0.28489714 0.23389109 0.16442608 0.9800706  0.32842948]]


# randn()

In [13]:
var2 = np.random.randn(5)

print(var2)

[-0.11278521 -0.15660131  0.15135939  1.57601789  0.5166635 ]


# ranf()

In [15]:
var3 = np.random.ranf(4)

print(var3)

[0.40224666 0.04997014 0.18195377 0.74665353]


# randint()

In [16]:
var4 = np.random.randint(5,20,5)

print(var4)

[17 16 14  5  8]
