# Zeros

In [27]:
import numpy as np
ar_zero=np.zeros(4)

print(ar_zero)

[0. 0. 0. 0.]


# ones

In [28]:
ar_ones=np.ones(4)

print(ar_ones)

[1. 1. 1. 1.]


# empty

In [29]:
ar_em = np.empty(4)

print(ar_em)

[1. 1. 1. 1.]


# Range

In [30]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


# Diagonal

In [31]:
ar_dig = np.eye(3)
print(ar_dig)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
ar_dig = np.eye(3,5)
print(ar_dig)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# Linespace

In [33]:
ar_lin = np.linspace(0,10,5)
print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]
